### PR TITLE
Fixes #254 move blocking call in db to sync

### LINKED ISSUE #254: Move blocking `db` call to sync
Currently calling `api/db` with the `transaction-time` argument blocks until the DB sees a transaction that is past this time. 

This issue is about potentially moving this blocking behavour to `sync` where `sync` could take a new `transaction-time` as a 3rd argument. 

The motivation for this is for aesthetics / intuitive API. `sync` is more where you'd expect the blocking behavour, `db` probably you wouldn't expect it there.

### PR DESCRIPTION
**Pull request by jonpither**
I will review the docstrings etc, but wanted to set out this PR to show the direction, and get feedback.

### CODE REVIEW

**Review by hraberg — COMMENTED** [review]
Looks good, but two questions:

1. We discussed renaming the method, did we decide against, or did we forget about it?
2. I feel that timeout should be the last argument, for reasons I cannot fully motivate.

**Comment by jonpither** [comment]
Agree with 2.

I can't remember what we finalised on with 1. I just decided to make the change, in the view that's easy to finalise the details after, so I'm happy to rename the method. I've just lost my strong opinion on it :-)

**Comment by hraberg** [comment]
I don't mind the name as such, but usually want to avoid things clashing with `clojure.core`. That said, once someone has an opinion they can state it and use query replace, so we can park that.

**Review by hraberg — CHANGES_REQUESTED** [review]
We want to change argument order from duration, date to date, duration.

**Comment by hraberg** [comment]
Also, to state the obvious, the name of this function is very old and not really related to this issue itself.

**Comment by jonpither** [comment]
I think we'll stick with `sync` for now - we can always change in a subsequent release whilst we're in alpha.

Besides @malcolmsparks makes an eloquent case and impassioned defence for retaining `sync`.

**Comment by jonpither** [comment]
I changed the arg order, good for merging, assuming we can rename `sync` at a later date (and we should discuss again).

**Pull request merged**
