### PR TITLE
Improve next kv usage

### PR DESCRIPTION
**Pull request by hraberg**
Contains crux.indexer cleanup and simplification. Better namespace isolation.

Also adds ae and av indexes to avoid calls to seek, but this isn't directly proven to be faster. Adds ~5% size. Can back these changes out if we prefer to wait?

### CODE REVIEW

**Comment by hraberg** [comment]
The added changes crux.kv-indexer are a mix, but the new indexes could back out. Another reason to keep the new indexes is that we can move AECV and ECAV.

**Review by jarohen — COMMENTED** [review]
As discussed, could we move AECV -> ECAV?

**Comment by hraberg** [comment]
Thanks, yes, will move to ECAV tomorrow or later today.

**Comment by hraberg** [comment]
Now includes ECAV change, can be merged when build passes.

**Pull request merged**
