### PR TITLE
gh236/lru : fix key pooling

### PR DESCRIPTION
**Pull request by spacegangster**
tests are passing

### CODE REVIEW

**Review by hraberg — CHANGES_REQUESTED** [review]
I mean you can replace the entire `compute-if-absent` in `get-objects` with a call to `get-single-object`. No need for Java interop, you can use `db/get-single-object`.

**Comment by spacegangster** [comment]
@hraberg comment is addressed now.
Tests are good on openjdk-11 and hotspot-10 and there's even *a* pass on hotspot-8

**Comment by spacegangster** [comment]
@hraberg  I ran watdiv suite (is it the right one?) once on master branch and twice with our pooled buffers fix. I don’t see much variability.
On master
```
"Elapsed time: 268540.987686 msecs"
"Elapsed time: 117.944926 msecs"
```
On the branch
```
"Elapsed time: 279184.388337 msecs"
"Elapsed time: 107.121264 msecs"
...
"Elapsed time: 258216.086621 msecs"
"Elapsed time: 165.383238 msecs"
```

**Comment by hraberg** [comment]
The WatDiv suite requires a environment variable to be set to run, the full suite takes a very long time (hours) to run, I usually run a subset. But as mentioned elsewhere, for this case you just need something that should show the difference, so almost any non trivial test might do.

**Review by hraberg — APPROVED** [review]

**Pull request merged**
