### PR TITLE
Testing transit params on pg2

### PR DESCRIPTION
**Pull request by egg-juxt**
Related: https://github.com/igrishaev/pg2/issues/18

These are some pg2-specific tests for testing the transit type. There are 2 tests, one providing the encoded string directly, another using pg2 custom types.

### CODE REVIEW

**Comment by egg-juxt** [comment]
@jarohen , are these pg2-specific tests interesting to have in our test battery?

**Comment by egg-juxt** [comment]
- [x] We should test transit decoding using connection option "fallback_output_format=transit"

**Comment by jarohen** [comment]
> @jarohen , are these pg2-specific tests interesting to have in our test battery?

absolutely, yep :slightly_smiling_face:

**Review by jarohen — APPROVED** [review]

**Comment by egg-juxt** [comment]
Added testing with transit as format for the output results, as well as for binary transit.

@jarohen , @mbutlerw , do we really want to use the transit+json format when doing pg binary encoding, or should we switch to transit+msgpack for that case?

**Comment by jarohen** [comment]
> do we really want to use the transit+json format when doing pg binary encoding, or should we switch to transit+msgpack for that case?

probably, yep - but I wouldn't couple that change into here :) and tbh I'd look into getting #3844 solved first, see how people use it, and then we're in a better place to make that call

**Pull request merged**
