### PR TITLE
MySQL-compliant queries

### PR DESCRIPTION
**Pull request by siefca**
Added MySQL-compliant queries for creating tx_events table and index.

### CODE REVIEW

**Comment by jonpither** [comment]
Hi @siefca - thanks for this PR - appreciated. Will test it against our mysql setup and merge if it passes. Hope to get it soon.

**Comment by jonpither** [comment]
Passed locally against my setup.

**Comment by refset** [comment]
Yep, seems like this is good to merge :)

@siefca before we do merge though, please could you complete this short CLA .rtf form and send it to us via email? https://www.opencrux.com/docs#contributing-cla

**Comment by siefca** [comment]
@refset, @jonpither: Thanks, guys. I've sent the CLA via e-mail.

BTW, how about making `v` column `LONGBLOB` instead of `BLOB`. It can hold max. 4GB of data whereas `BLOB` can only store 64kB.

**Comment by jarohen** [comment]
cheers @siefca, rebased and merged :smile:

**Pull request closed without merging**
