### PR TITLE
Fix error in pgwire when rendering sets as json in the xt.txs.error column

### LINKED ISSUE #3866: pgwire should handle xt.txs errors containing symbols/sets/etc.
While attempting `SELECT * FROM xt.txs` (not sure on the exact INSERT that might have caused this yet)

```
ERROR xtdb.pgwire - #error {
 :cause Unexpected type encountered by pgwire (class clojure.lang.Symbol)
 :via
 [{:type java.lang.Exception
   :message Unexpected type encountered by pgwire (class clojure.lang.Symbol)
   :at [xtdb.pgwire$json_clj invokeStatic pgwire.clj 558]}]
 :trace
 [[xtdb.pgwire$json_clj invokeStatic pgwire.clj 558]
  [xtdb.pgwire$json_clj invoke pgwire.clj 479]
  [clojure.core$update_vals$fn__8985 invoke core.clj 8141]
  [clojure.lang.PersistentArrayMap kvreduce PersistentArrayMap.java 475]
  [clojure.core$fn__8555 invokeStatic core.clj 6987]
  [clojure.core$fn__8555 invoke core.clj 6967]
  [clojure.core.protocols$fn__8283$G__8278__8292 invoke protocols.clj 174]
  [clojure.core$reduce_kv invokeStatic core.clj 6998]
  [clojure.core$update_vals invokeStatic core.clj 8142]
  [clojure.core$update_vals invoke core.clj 8132]
  [xtdb.pgwire$json_clj invokeStatic pgwire.clj 548]
  [xtdb.pgwire$json_clj invoke pgwire.clj 479]
  [clojure.core$mapv$fn__8565 invoke core.clj 7059]
  [clojure.lang.PersistentVector reduce PersistentVector.java 418]
  [clojure.core$reduce invokeStatic core.clj 6964]
  [clojure.core$mapv invokeStatic core.clj 7050]
  [clojure.core$mapv invoke core.clj 7050]
  [xtdb.pgwire$json_clj invokeStatic pgwire.clj 544]
  [xtdb.pgwire$json_clj invoke pgwire.clj 479]
  [clojure.core$update_vals$fn__8985 invoke core.clj 8141]
  [clojure.lang.PersistentArrayMap kvreduce PersistentArrayMap.java 475]
  [clojure.core$fn__8555 invokeStatic core.clj 6987]
  [clojure.core$fn__8555 invoke core.clj 6967]
  [clojure.core.protocols$fn__8283$G__8278__8292 invoke protocols.clj 174]
  [clojure.core$reduce_kv invokeStatic core.clj 6998]
  [clojure.core$update_vals invokeStatic core.clj 8142]
  [clojure.core$update_vals invoke core.clj 8132]
  [xtdb.pgwire$json_clj invokeStatic pgwire.clj 548]
  [xtdb.pgwire$json_clj invoke pgwire.clj 479]
  [xtdb.pgwire$json_clj invokeStatic pgwire.clj 552]
  [xtdb.pgwire$json_clj invoke pgwire.clj 479]
  [clojure.core$comp$fn__5895 invoke core.clj 2586]
  [xtdb.pgwire$write_json invokeStatic pgwire.clj 1093]
  [xtdb.pgwire$write_json invoke pgwire.clj 1092]
  [xtdb.pgwire$cmd_exec_query$fn__42103$fn__42105 invoke pgwire.clj 1205]
  [clojure.core$mapv$fn__8565 invoke core.clj 7059]
  [clojure.lang.PersistentVector reduce PersistentVector.java 418]
  [clojure.core$reduce invokeStatic core.clj 6964]
  [clojure.core$mapv invokeStatic core.clj 7050]
  [clojure.core$mapv invoke core.clj 7050]
  [xtdb.pgwire$cmd_exec_query$fn__42103 invoke pgwire.clj 1197]
  [clojure.lang.FnInvokers invokeOO FnInvokers.java 247]
  [xtdb.operator.project.ProjectCursor$reify__38069 accept project.clj 133]
  [xtdb.operator.rename.RenameCursor$reify__38862 accept rename.clj 39]
  [xtdb.operator.scan.TrieCursor$fn__36568 invoke scan.clj 293]
  [xtdb.operator.scan.TrieCursor tryAdvance scan.clj 244]
  [xtdb.operator.rename.RenameCursor tryAdvance rename.clj 29]
  [xtdb.operator.project.ProjectCursor tryAdvance project.clj 119]
  [xtdb.query$wrap_cursor$reify__40776 tryAdvance query.clj 84]
  [java.util.Spliterator forEachRemaining Spliterator.java 332]
  [xtdb.pgwire$cmd_exec_query invokeStatic pgwire.clj 1184]
  [xtdb.pgwire$cmd_exec_query invoke pgwire.clj 1174]
  [xtdb.pgwire$execute_portal invokeStatic pgwire.clj 1510]
  [xtdb.pgwire$execute_portal invoke pgwire.clj 1495]
  [xtdb.pgwire$eval42290$fn__42293$fn__42296 invoke pgwire.clj 1537]
  [xtdb.pgwire$eval42290$fn__42293 invoke pgwire.clj 1525]
  [clojure.lang.MultiFn invoke MultiFn.java 234]
  [xtdb.pgwire$handle_msg invokeStatic pgwire.clj 1560]
  [xtdb.pgwire$handle_msg invoke pgwire.clj 1553]
 ```

Selecting the non-error columns works okay.

### PR DESCRIPTION
**Pull request by egg-juxt**

### CODE REVIEW

**Comment by refset** [comment]
The original report suggested a symbol was the culprit - we don't have a repro for that, but could you see how the code fails (if it at all) when you have a symbol in the mix at the REPL?

**Comment by egg-juxt** [comment]
> The original report suggested a symbol was the culprit - we don't have a repro for that, but could you see how the code fails (if it at all) when you have a symbol in the mix at the REPL?

I suspected about a symbol being the issue, but it was actually the Set.

It seems we don't support storing Clojure symbols?
```
(xt/submit-tx tu/*node* [[:put-docs :test {:xt/id 1 :v 'my/symbol}]])
```
throws
```
java.lang.UnsupportedOperationException: unknown object type: class clojure.lang.Symbol
	at xtdb.Types.valueToArrowType(Types.kt:147)
```

**Comment by refset** [comment]
We don't support storing symbols directly, but there is a `clj-form` / `ClojureForm` type which handles symbols IIUC. I believe it may get used in the `xt.txs` error path due to the use of the 'transit' type here: https://github.com/xtdb/xtdb/blob/4db8c4b407b02c222f36607188d8ed3f97cb7192/core/src/main/clojure/xtdb/indexer.clj#L584

To recap, the Symbol error was:
```
ERROR xtdb.pgwire - #error {
 :cause Unexpected type encountered by pgwire (class clojure.lang.Symbol)
```
I think fixing the Set error is related, but would be surprised if the possibility for this Symbol error wasn't still lurking.

**Comment by FiV0** [comment]
Thanks :pray: @egg-juxt . I also added the symbol case.

**Pull request merged**
