### PR TITLE
Transaction function contexts, #865

### LINKED ISSUE #865: Transaction function impls are passed a context
Currently, transaction functions are passed a database value at the current vt/tt and their args - we'd like to offer more:

* Ability to get a database at any vt/tt
* Details about the current transaction - transaction-time/transaction-id, other operations, etc - replacing the current dynamic var
* Anything else?

### PR DESCRIPTION
**Pull request by jarohen**
resolves #865.

See tx-test changes for what this looks like from a user's PoV

Anything else we should expose as part of this context?

Also:
* Documentation added for transaction functions
* If a transaction function returns `false` we abort the transaction
* Feature flag removed :smile:

### CODE REVIEW

**Comment by hraberg** [comment]
Other things that could go in the context are the things currently sitting in the dynamic var, the submitted tx itself, that is, its timestamps and id (and maybe also its ops).

**Comment by jarohen** [comment]
@hraberg - yep - I've put `:crux.tx/current-tx` on the context which has the tx-time and tx-id, could consider putting the ops on there too

**Review by hraberg — APPROVED** [review]

**Comment by hraberg** [comment]
Reflecting a bit on this - would it be somewhat cleaner to provide access to the transaction via a method on the context instead of just grabbing a "magic" keyword?

**Comment by jarohen** [comment]
@hraberg replaced magic keyword with `crux.api/indexing-tx` as discussed :smile:

**Pull request merged**
