### PR TITLE
Add Azure Blob Storage doc-store module (crux-azure-blobs)

### PR DESCRIPTION
**Pull request by luposlip**
- [x] Store documents in Azure Blob Storage
- [x] Read documents from Azure Blob Storage
- [x] Retrieve results via `crux/q`
- [x] Retrieve documents via `crux/entity`
- [x] Make `crux-blobs` available from main `crux` build
- [x] Serialization via `nippy`
- [x] Add test
- [x] Rename to `crux-azure-blobs`
- [x] Merge conflict with main `master`
- [x] Refactor to new module configuration
- [x] Update documentation ^

### CODE REVIEW

**Comment by luposlip** [comment]
@jarohen I'm not really sure why this error occurs?
```
    test-compaction-leaves-replayable-log - crux.compaction-test
    expected: (= 2 (count (api/entity-history (api/db api2) :foo :asc))). actual: (not (= 2 1))
```

**Comment by jarohen** [comment]
Hi @luposlip - unfortunately this is an intermittent test failure (on master, too) which I haven't managed to track down yet. I've opened an issue for it (#1078) but, for now, safe to assume it's not your code that's breaking it.

**Comment by jonpither** [comment]
Thanks @luposlip for this! I think we ought rename to `crux-azure` for discoverability of the module.

**Comment by jonpither** [comment]
Relates to https://github.com/juxt/crux/issues/995

**Comment by luposlip** [comment]
> Thanks @luposlip for this! I think we ought rename to `crux-azure` for discoverability of the module.

No problem @jonpither - but shouldn't it be `crux-azure-blobs` then?

**Comment by jonpither** [comment]
@luposlip yep, could be `crux-azure-blobs` - will ponder and discuss today.

**Comment by luposlip** [comment]
Alright @jonpither let me know what you decide, then I'll update accordingly.

**Comment by jonpither** [comment]
Hi @luposlip. We've decided to go with your suggestion of `crux-azure-blobs`! Thanks.

**Comment by jarohen** [comment]
> Hi @luposlip - unfortunately this is an intermittent test failure (on master, too) which I haven't managed to track down yet. I've opened an issue for it (#1078) but, for now, safe to assume it's not your code that's breaking it.

@luposlip fixed in master :smile:

**Comment by jarohen** [comment]
Hey again @luposlip - I've just landed #1010 which is a sizeable change in declaring Crux modules. 

Happy to help out with the merge - if you'd like I can update your branch directly?

(There's a couple of links to new docs and a migration guide in that PR if you're interested :) )

**Comment by luposlip** [comment]
Hey @jarohen ,

Unless you're in a hurry I'd like to do it in order to get to know the new structure of modules?

Of course I'm fine with you doing it also, if it's a minor refactoring for you and you'd like to finish the merge.

Best,
Henrik

**Comment by jarohen** [comment]
@luposlip: of course, go for it - let me know if I can provide any pointers :)

**Comment by luposlip** [comment]
I'll find some time tomorrow and let you know how it goes!

**Comment by luposlip** [comment]
@jarohen I'm getting an error in `crux/query_state.clj` when I try to start a repl after my reconfig:

```clojure
Exception in thread "main" Syntax error compiling at (crux/query_state.clj:1:1).
	at clojure.lang.Compiler.load(Compiler.java:7648)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:459)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6839.invoke(core.clj:6126)
	at clojure.core$load.invokeStatic(core.clj:6125)
	at clojure.core$load.doInvoke(core.clj:6109)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5908)
	at clojure.core$load_one.invoke(core.clj:5903)
	at clojure.core$load_lib$fn__6780.invoke(core.clj:5948)
	at clojure.core$load_lib.invokeStatic(core.clj:5947)
	at clojure.core$load_lib.doInvoke(core.clj:5928)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$load_libs.invokeStatic(core.clj:5985)
	at clojure.core$load_libs.doInvoke(core.clj:5969)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$require.invokeStatic(core.clj:6007)
	at clojure.core$require.doInvoke(core.clj:6007)
	at clojure.lang.RestFn.invoke(RestFn.java:482)
	at crux.api$eval146$loading__6721__auto____147.invoke(api.clj:1)
	at crux.api$eval146.invokeStatic(api.clj:1)
	at crux.api$eval146.invoke(api.clj:1)
```

**Comment by jarohen** [comment]
Hey @luposlip - have you re-run `lein sub javac` since those changes? We've changed a number of the Java classes, which Lein doesn't recompile without a poke. You may also need to `lein sub install` to pick up dependency changes

James

**Comment by luposlip** [comment]
Thanks @jarohen, that worked.

[UPDATE: My `dev/user.clj` namespace now works]

[UPDATE: The test now works too ;)]

**Comment by luposlip** [comment]
@jarohen the failure in the test run seems to be from somewhere else?
```
Testing crux.kv.indexer-test
Error encountered performing task 'run' with profile(s): 'base,system,user,provided,dev,test'
```
[UPDATE] Well, that was intermittent ;)

**Comment by luposlip** [comment]
@jarohen can I assist with testing/setting up an Azure Storage Account etc.?

**Review by jarohen — APPROVED** [review]
Big thanks for this @luposlip, a great addition to the Crux ecosystem!

We've got a bit more work to do internally to get this running on our CI, but I've run it locally and I'm happy to get this included in our 1.12.0 release. I've made a couple of minor edits - particularly, porting the recent changes to the S3 docs over to Azure Blobs too, and I'll mark it 'alpha' for a release or two just in case we need to iterate on the API (not that I can see anything immediately obvious as yet).

Cheers!

James

**Pull request merged**
